### ISSUE TITLE
This embeds youtube link using a self-closing iframe, even though iframe is not self-closing tag

### ISSUE THREAD

**Issue by philip-bl** [kmonsoor/lektor-embed-x#2]
As a result, my browsers consider all tags that go after the iframe as being inside it, and everything that goes after that iframe disappears.

`<iframe src="https://youtube.com/something" />` - this is wrong.

`<iframe src="https://youtube.com/something"></iframe>` - this is right.

This is a problem at least in chrome and firefox on ubuntu.

**Comment by philip-bl** [comment]
This is embedX's fault: https://github.com/kmonsoor/embedX/issues/4

**Comment by kmonsoor** [comment]
fixed by https://github.com/kmonsoor/embedX/pull/5
